### ISSUE TITLE
Breaking while histogramming over number of root files

### ISSUE THREAD

**Issue by belargej** [pcbend/GRUTinizer#72]
I have 10 root files, I want to run them and histogram with them, and I use the following command:

grutinizer -gH Run*.root ../config/values.val ../config/invmap_37Ar.inv

When I get to ~48k events (halfway through) I get a break.

I opened grutinizer in gdb, and ran it with the above arguments, and it makes it to the end of the sort no problem.

**Comment by pcbend** [comment]
Next time you get a break can you post the output here?

**Comment by belargej** [comment]
```
GRizer [0] 
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 5 (Thread 0x7f10a70dd700 (LWP 10549)):
#0  0x00007f10aceb7453 in select () at ../sysdeps/unix/syscall-template.S:82
#1  0x00007f10a73c1059 in ?? () from /usr/lib/libtcl8.5.so.0
#2  0x00007f10ad173b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#3  0x00007f10acebd95d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#4  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7f10a5ab7700 (LWP 10550)):
#0  pthread_cond_wait

GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:162
#1  0x00007f10ad8d471c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f10b42c971c in ThreadsafeQueue<TUnpackedEvent*>::Push (this=0x3176798, obj=0x7f106e8b1c20) at /user/belarge/Programs/GRUTinizer/include/ThreadsafeQueue.h:61
#3  0x00007f10b37b14cd in TChainLoop::Iteration (this=0x2ff7f50) at libraries/TLoops/TChainLoop.cxx:88
#4  0x00007f10b37ab9e6 in StoppableThread::Loop (this=0x2ff7f50) at libraries/TLoops/StoppableThread.cxx:183
#5  0x00007f10ad8d7400 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f10ad173b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#7  0x00007f10acebd95d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#8  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7f10a52b6700 (LWP 10551)):
#0  0x00007f10ad17b91d in nanosleep () at ../sysdeps/unix/syscall-template.S:82
#1  0x00007f10b37acd2b in sleep_for<long, std::ratio<1l> > (__rtime=...) at /usr/include/c++/4.7/thread:277
#2  StoppableThread::status_out_loop () at libraries/TLoops/StoppableThread.cxx:221
#3  0x00007f10ad8d7400 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f10ad173b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#5  0x00007f10acebd95d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#6  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7f10a4ab5700 (LWP 10552)):
#0  0x00007f10ace8d0ad in __libc_waitpid (pid=10945, stat_loc=<optimized out>, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:41
#1  0x00007f10ace21989 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:149
#2  0x00007f10ace21cc0 in __libc_system (line=<optimized out>) at ../sysdeps/posix/system.c:190
#3  0x00007f10b262ce0c in TUnixSystem::StackTrace() () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libCore.so.5
#4  0x00007f10b262f6b3 in TUnixSystem::DispatchSignals(ESignals) () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libCore.so.5
#5  <signal handler called>
#6  0x00007f1098000698 in ?? ()
#7  0x00007f10b42c7e85 in ~TPreserveGDirectory (this=<synthetic pointer>, __in_chrg=<optimized out>) at /user/belarge/Programs/GRUTinizer/include/TPreserveGDirectory.h:9
#8  TCompiledHistograms::Fill (this=0x3176628, detectors=...) at libraries/THistogramming/TCompiledHistograms.cxx:155
#9  0x00007f10b42c8701 in THistogramLoop::Iteration (this=0x31765b0) at libraries/THistogramming/THistogramLoop.cxx:60
#10 0x00007f10b37ab9e6 in StoppableThread::Loop (this=0x31765b0) at libraries/TLoops/StoppableThread.cxx:183
#11 0x00007f10ad8d7400 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f10ad173b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#13 0x00007f10acebd95d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#14 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f10b6375100 (LWP 10540)):
#0  0x00007f10aceb7453 in select () at ../sysdeps/unix/syscall-template.S:82
#1  0x00007f10b262f825 in TUnixSystem::UnixSelect(int, TFdSet*, TFdSet*, long) () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libCore.so.5
#2  0x00007f10b2630112 in TUnixSystem::DispatchOneEvent(bool) () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libCore.so.5
#3  0x00007f10b268df56 in TSystem::InnerLoop() () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libCore.so.5
#4  0x00007f10b268fb44 in TSystem::Run() () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libCore.so.5
#5  0x00007f10b267fcaf in TApplication::Run(bool) () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libCore.so.5
#6  0x00007f10af7c5d67 in TRint::Run(bool) () from /mnt/misc/sw/x86_64/Debian/7/root/gnu/5.34.32/lib/libRint.so.5
#7  0x0000000000401906 in main (argc=15, argv=0x7fff7877c338) at src/grutinizer.cxx:94
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f1098000698 in ?? ()
#7  0x00007f10b42c7e85 in ~TPreserveGDirectory (this=<synthetic pointer>, __in_chrg=<optimized out>) at /user/belarge/Programs/GRUTinizer/include/TPreserveGDirectory.h:9
#8  TCompiledHistograms::Fill (this=0x3176628, detectors=...) at libraries/THistogramming/TCompiledHistograms.cxx:155
#9  0x00007f10b42c8701 in THistogramLoop::Iteration (this=0x31765b0) at libraries/THistogramming/THistogramLoop.cxx:60
#10 0x00007f10b37ab9e6 in StoppableThread::Loop (this=0x31765b0) at libraries/TLoops/StoppableThread.cxx:183
#11 0x00007f10ad8d7400 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f10ad173b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#13 0x00007f10acebd95d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#14 0x0000000000000000 in ?? ()

===========================================================


terminate called without an active exception
Aborted
```

Sorry it took me a while to comment, didnt see your email.  This isnt super pressing, I can work around it. I just didnt want to forget about it.
